### PR TITLE
Add missing gtk+ dependency on Windows

### PR DESCRIPTION
**Pull request by melund**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Weasyprint documentation states that  [GTK+ is required on Windows](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows). This PR adds gtk3 as dependency on Windows. 

This fixes the `OSError: cannot load library 'gobject-2.0-0'"`([link](https://github.com/assafelovic/gpt-researcher/issues/166)) error I get when using the current package.

### CODE REVIEW

**Comment by liZe** [comment]
Hi!

Thanks for this pull request.

This bug was actually supposed to be already fixed by adding glib to the list of dependencies: https://github.com/conda-forge/weasyprint-feedstock/issues/23. So this workaround doesn’t work.

> Weasyprint documentation states that [GTK+ is required on Windows](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows)

GTK+ is not required on Windows, it’s just the easiest way to get Pango and its dependencies (including glib) installed when you don’t use a package manager like Conda.

Instead of using another workaround, I’d prefer to get the original problem solved: https://github.com/conda-forge/glib-feedstock/issues/104. Otherwise, the most reliable fix for now seems to be reinstalling glib manually after installing WeasyPrint.

**Comment by melund** [comment]
> Otherwise, the most reliable fix for now seems to be reinstalling glib manually after installing WeasyPrint.

That is no solution me. A manual installation will not work in a automated workflow where we expect conda to create a working environment. I don't think it is unreasonable to add gtk as a dependency, given that is what the official documentation ask users to install. 

But I don't mind adding the low level dependencies directly to the recipe instead of GTK+, if that can solve it. @liZe Do you want me to try that?

**Comment by liZe** [comment]
> That is no solution for me. A manual installation will not work in an automated workflow where we expect conda to create a working environment.

I mean that you can call `conda install glib` after calling `conda install weasyprint`, as proposed in #23.

> I don't think it is unreasonable to add GTK as a dependency

The problem is not to add GTK as a dependency (even if it’s ugly indeed :smile:.) The problem is that `glib` had been previously added to the list to "solve" the exact same bug. And that was even just "temporary", according to the comment! So, adding GTK may work for you today, but it may not work tomorrow, or may not work for other users, for some reason I’d like to understand.

I don’t like to refuse pull requests at all 😢, but I won’t add more and more dependencies just because they sometimes solve the bug as a side effect. If it works for you, nothing prevents you from adding and maintaining this hack in your stack by installing GTK when installing WeasyPrint. Let’s hope it won’t break for you in the future, but if it does I won’t be the one to blame!

> given that is what the official documentation ask users to install.

As I wrote this official documentation, I can tell you for sure that there’s no reason to install GTK when using WeasyPrint with Conda :smile:. GTK is not a dependency of WeasyPrint, it’s just an easy way to install these WeasyPrint’s dependencies on Windows when you don’t use a package manager such as Conda.

As far as I can tell, the bug is actually https://github.com/conda-forge/glib-feedstock/issues/104, and fixing it is the only reliable way to fix the problem with WeasyPrint’s package.

**Comment by melund** [comment]
> As I wrote this official documentation, I can tell you for sure that there’s no reason to install GTK when using WeasyPrint with Conda

@liZe, Good point, 😆 I can also confirm that reinstalling glib `conda install --force-reinstall glib` after environment creation fixes the problem. 

But it got me thinking that maybe the problem is not the `glib` package, but some other packages which messes up the DLL's after installation. Or maybe the order packages are linked into the environment.

I was using weasyprint through some sphinx plugin (`sphinx-simplepdf`) for which there wasn't any conda-packages. So I installed all dependencies with conda, and then finally did a `pip install sphinx-simplepdf´. That part only worked if I conda installed `weasyprint` and then a `glib` reinstall. 

But yesterday I got the conda-forge package for `sphinx-simplepdf` merged. That fixed it for me. Now I can simple do `conda install -c conda-forge sphinx-simplepdf`, which gives me a working environment. Very confusing.

**Pull request closed without merging**
