### PR TITLE
Make noarch

### LINKED ISSUE #15: Windows support
I think that Windows was not supported because one of the dependencies was not available on Windows. But as far as I can tell, all the dependencies are now available. @mrandrewandrade Do you know what’s needed to add the Windows support?

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #15 

This PR makes the following changes:

1. Makes package [noarch](https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python).
2. Re-rendered with new smithy.
3. Adds `console_scripts` entry points.
4. Adds python minimum of  `>=3.6`.
5. Sorts required packages (Through [Grayskull](https://github.com/conda-incubator/grayskull)).
6. Cleans `host`.
7. Sets minimum for pango.
8. Specifies higher pyphen version.
9. Adds cairo >=1.15.4 as outlined in https://weasyprint.readthedocs.io/en/stable/install.html#id5 If this is not required due to cairocffi etc. I'll remove it again.
10. Adds gdk-pixbuf. This can also be made optional, let me know.
11. Drops xorg-libxrender xorg-libxext which is not in the setup.cfg. let me know if that's actually needed and I'll add it back.
12. Add some more tests to check dependencies.
13. Updates to 52.3

Edit: 

Also closes #19

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Just to add, I also added the unit tests but removed them again since some of them didn't pass and I wasn't able to confirm whether that is due to conda-forge or upstream The output was similar to the failing tests upstream. Let me know if they should be added.

**Comment by BastianZim** [comment]
@liZe @mrandrewandrade Would be ready for review, thanks!

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
I have also updated this to incorporate the new version now.

**Comment by liZe** [comment]
Thanks a lot for this PR!

> Just to add, I also added the unit tests but removed them again since some of them didn't pass and I wasn't able to confirm whether that is due to conda-forge or upstream The output was similar to the failing tests upstream. Let me know if they should be added.

Having `weasyprint --help` working is really good news. If possible, I’d be interested in having the logs of the failing tests, just to be sure that it’s the same problem as the failing tests upstream.

**Comment by BastianZim** [comment]
Happy to help! :)
Let me just create another PR with the tests, then you can verify everything for yourself.

**Comment by liZe** [comment]
> Let me just create another PR with the tests, then you can verify everything for yourself.

Thanks a lot!

The errors come from missing fonts. Fontconfig complains because no font is installed, and it makes the tests fail.

You can either install fonts before launching tests, or just rely on `weasyprint --help`.

One last question: is the build tested on macOS and Windows too?

**Comment by liZe** [comment]
> Is it just a case of installing Fontconfig, or does it need extra options? Since Fontconfig is on conda-forge, I could easily include that.

Fontconfig is already installed, and it is correctly configured accordingly to what I can see. The problem seems to be that no font is installed on Linux.

> No, since it's noarch, only Linux will be tested. Is that a problem?

If we can blindly trust that Conda packages behave the same way on different platforms, and that Python can load libraries correctly on Windows and macOS, then there’s no need to check 😄 🤞🏽.

**Comment by BastianZim** [comment]
> Fontconfig is already installed, and it is correctly configured accordingly to what I can see. The problem seems to be that no font is installed on Linux.

Ok I would then suggest going only with the import and pip tests since this is definitely something on the conda-forge side and not a package error. 
This is the current approach so the package would be ready for review/merge from my side then. 

> If we can blindly trust that Conda packages behave the same way on different platforms, and that Python can load libraries correctly on Windows and macOS, then there’s no need to check 😄 🤞🏽.

Yes, that basically the premise of noarch packages. If the packages fulfil the requirements in the [docs](https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python) they can be built for a generic host with the "fine tuning" being done during installation. This applies even if dependencies aren't available on a particular host as conda would then inform the user and not install the package. 
For this, it is important though that all packages that are required are listed in the recipe and not only in the docs with a notice to manually install separately later, as conda will then not be able to determine if all packages can be installed on the specific host. I did try to add all packages that I could find in the docs etc. but it might be good if you could just double check that to make sure that I'm not missing anything?

**Comment by liZe** [comment]
> I did try to add all packages that I could find in the docs etc. but it might be good if you could just double-check that to make sure that I'm not missing anything?

OK, I’ll check that nothing’s missing, and merge if everything’s fine. Thanks a lot for your contribution!

**Comment by BastianZim** [comment]
Perfect, thank you very much! Was a pleasure! :)

**Comment by BastianZim** [comment]
@liZe Just one last question: I saw the announcement on WeasyPrint that you are/were switching to pydyf but conda-forge is still tracking the releases with Cairo, is that correct? Otherwise, I'd create a new PR with the specs from the `pyproject.toml` file.

**Comment by liZe** [comment]
> @liZe Just one last question: I saw the announcement on WeasyPrint that you are/were switching to pydyf but conda-forge is still tracking the releases with Cairo, is that correct?

It’s correct.

> But let me know if you'd like some help with bringing pydyf to conda-forge.

Thanks a lot, we’ll let you know when pydyf is ready to be packaged.

**Pull request merged**
