### PR TITLE
Update meta.yaml

### LINKED ISSUE #3: Python restricted to 3.7?
Issue:

Hi!
To me, it seems like the python version is restricted to 3.7. When I type

```
bash-4.2$ conda search weasyprint --info --channel conda-forge
Loading channels: done
weasyprint 47 py37h73018de_0
----------------------------
file name   : weasyprint-47-py37h73018de_0.tar.bz2
name        : weasyprint
version     : 47
build       : py37h73018de_0
build number: 0
size        : 534 KB
license     : BSD-3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/weasyprint-47-py37h73018de_0.tar.bz2
md5         : 668526d8564b4235ae3bb11b7d8085aa
timestamp   : 2019-07-22 15:29:33 UTC
dependencies: 
  - cairocffi >=0.9.0
  - cairosvg >=2.4.0
  - cffi >=0.6
  - cssselect2 >=0.1
  - html5lib >=0.999999999
  - pango >=1.42.4,<1.43.0a0
  - pyphen >=0.8
  - python >=3.7,<3.8.0a0
  - setuptools >=39.2.0
  - tinycss2 >=1.0.0
  - xorg-libxext
  - xorg-libxrender


weasyprint 48 py37h73018de_0
----------------------------
file name   : weasyprint-48-py37h73018de_0.tar.bz2
name        : weasyprint
version     : 48
build       : py37h73018de_0
build number: 0
size        : 541 KB
license     : BSD-3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/weasyprint-48-py37h73018de_0.tar.bz2
md5         : 3e6b5be5d24f099cce7c37c7190b441b
timestamp   : 2019-08-03 00:13:59 UTC
dependencies: 
  - cairocffi >=0.9.0
  - cairosvg >=2.4.0
  - cffi >=0.6
  - cssselect2 >=0.1
  - html5lib >=0.999999999
  - pango >=1.42.4,<1.43.0a0
  - pyphen >=0.8
  - python >=3.7,<3.8.0a0
  - setuptools >=39.2.0
  - tinycss2 >=1.0.0
  - xorg-libxext
  - xorg-libxrender
```

This obviously made it impossible to specify python 3.6. I found a workaround, to specify my yml file with pip:

```
name: pdf_gen
channels:
   - conda-forge
   - default
dependencies:
   # Basic
   - python=3.6.*
   - pip
   - conda

   # CI/CD
   - pytest
   - pylint

   # Genearate html to PDF
   - jinja2

   - pip:
     - weasyprint
```

I suppose it shouldn't be like this. Might there be something strange with my setup, or should something be fixed here? https://github.com/conda-forge/weasyprint-feedstock/blob/master/recipe/meta.yaml specify "python >3.5"

I'm pretty new to the community, hope this is of any value...

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
</details>

```
$ conda info

     active environment : reportgen_env
    active env location : /home/<MY_USER>/miniconda3_versioned/envs/reportgen_env
            shell level : 2
       user config file : /home/<MY_USER>/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /home/<MY_USER>/miniconda3_versioned  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/<MY_USER>/miniconda3_versioned/pkgs
                          /home/<MY_USER>/.conda/pkgs
       envs directories : /home/<MY_USER>/miniconda3_versioned/envs
                          /home/<MY_USER>/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/3.10.0-862.11.6.el7.x86_64 rhel/7.5 glibc/2.17
                UID:GID : 355479:1115
             netrc file : None
           offline mode : False

```

### LINKED ISSUE #8: Unable to install under Python 3.8
Issue:
Cannot install under python 3.8

My issue:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - weasyprint -> python[version='2.7.*|3.5.*|3.6.*|3.6.9|3.6.9|3.6.9|>=2.7,<2.8.0a0|>=3.5|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*|>3.5',build='1_73_pypy|2_73_pypy|0_73_pypy']
  - weasyprint -> python[version='>=3.7,<3.8.0a0']

Your python: python=3.8


```
But according to the [Weasyprint website](https://weasyprint.org/start/), it should be available for Python 3.5+

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /usr/local/anaconda3/envs/environment_name:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0  
applaunchservices         0.2.1                      py_0  
appnope                   0.1.0                 py38_1001  
argh                      0.26.2                   py38_0  
astroid                   2.4.2                    py38_0  
atomicwrites              1.4.0                      py_0  
attrs                     19.3.0                     py_0  
autopep8                  1.5.4                      py_0  
babel                     2.8.0                      py_0  
backcall                  0.2.0                      py_0  
bleach                    3.1.5                      py_0  
boto3                     1.14.37                    py_0  
botocore                  1.17.39                    py_0  
brotlipy                  0.7.0           py38haf1e3a3_1000  
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.1           py38hed5b41f_0  
chardet                   3.0.4                 py38_1003  
cloudpickle               1.5.0                      py_0  
cryptography              2.9.2            py38ha12b0ac_0  
dbus                      1.13.16              h18a8e69_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20200713                   py_0  
docutils                  0.15.2                   py38_0  
entrypoints               0.3                      py38_0  
expat                     2.2.9                hb1e8313_2  
flake8                    3.8.3                      py_0  
future                    0.18.2                   py38_1  
gettext                   0.19.8.1             hb0f4f8b_2  
glib                      2.65.0               hc5f4afa_0  
icu                       58.2                 h0a44026_3  
idna                      2.10                       py_0  
imagesize                 1.2.0                      py_0  
importlib-metadata        1.7.0                    py38_0  
importlib_metadata        1.7.0                         0  
iniconfig                 1.0.1                      py_0  
intervaltree              3.0.2                      py_1  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.17.0           py38h39e3cac_0  
ipython_genutils          0.2.0                    py38_0  
isort                     4.3.21                   py38_0  
jedi                      0.15.2                   py38_0  
jinja2                    2.11.2                     py_0  
jmespath                  0.10.0                     py_0  
jpeg                      9b                   he5867d9_2  
jsonschema                3.2.0                    py38_1  
jupyter_client            6.1.6                      py_0  
jupyter_core              4.6.3                    py38_0  
keyring                   21.3.0                   py38_0  
lazy-object-proxy         1.4.3            py38h1de35cc_0  
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
libiconv                  1.16                 h1de35cc_0  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
libspatialindex           1.9.3                h0a44026_0  
libxml2                   2.9.10               h3b9e6c8_1  
libxslt                   1.1.34               h83b36ba_0  
lxml                      4.5.2            py38h63b7cb6_0  
markupsafe                1.1.1            py38h1de35cc_1  
mccabe                    0.6.1                    py38_1  
mistune                   0.8.4           py38h1de35cc_1001  
more-itertools            8.4.0                      py_0  
nbconvert                 5.6.1                    py38_1  
nbformat                  5.0.7                      py_0  
ncurses                   6.2                  h0a44026_1  
numpydoc                  1.1.0                      py_0  
openssl                   1.1.1g               haf1e3a3_1    conda-forge
packaging                 20.4                       py_0  
pandoc                    2.10                          0  
pandocfilters             1.4.2                    py38_1  
parso                     0.5.2                      py_0  
pathtools                 0.1.2                      py_1  
pcre                      8.44                 hb1e8313_0  
pexpect                   4.8.0                    py38_1  
pickleshare               0.7.5                 py38_1001  
pip                       20.2.2                   py38_0  
pluggy                    0.13.1                   py38_0  
prompt-toolkit            3.0.5                      py_0  
psutil                    5.7.0            py38h1de35cc_0  
ptyprocess                0.6.0                    py38_0  
py                        1.9.0                      py_0  
pycodestyle               2.6.0                      py_0  
pycparser                 2.20                       py_2  
pydocstyle                5.0.2                      py_0  
pyflakes                  2.2.0                      py_0  
pygments                  2.6.1                      py_0  
pylint                    2.5.3                    py38_0  
pyopenssl                 19.1.0                     py_1  
pypandoc                  1.5                pyh9f0ad1d_0    conda-forge
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38h655552a_2  
pyrsistent                0.16.0           py38h1de35cc_0  
pysocks                   1.7.1                    py38_1  
pytest                    6.0.1                    py38_0  
python                    3.8.5                h26836e1_0  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.4                      py_1  
python-language-server    0.31.9                   py38_0  
python.app                2                       py38_10  
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1                     py_0  
pyyaml                    5.3.1            py38haf1e3a3_1  
pyzmq                     19.0.1           py38hb1e8313_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 0.7.2                      py_0  
qtconsole                 4.7.5                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h1de35cc_0  
requests                  2.24.0                     py_0  
requests-file             1.5.1                      py_0  
rope                      0.17.0                     py_0  
rtree                     0.9.4                    py38_1  
s3transfer                0.3.3                    py38_1  
setuptools                49.3.1                   py38_0  
sip                       4.19.8           py38h0a44026_0  
six                       1.15.0                     py_0  
snowballstemmer           2.0.0                      py_0  
sortedcontainers          2.2.2                      py_0  
sphinx                    3.2.0                      py_0  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
spyder                    4.1.3                    py38_0  
spyder-kernels            1.9.3                    py38_0  
spyder-unittest           0.4.1                      py_0    spyder-ide
sqlite                    3.32.3               hffcf06c_0  
testpath                  0.4.4                      py_0  
tk                        8.6.10               hb0a8c7a_0  
tldextract                2.2.0                      py_0    conda-forge
toml                      0.10.1                     py_0  
tornado                   6.0.4            py38h1de35cc_1  
traitlets                 4.3.3                    py38_0  
ujson                     1.35             py38h1de35cc_0  
urllib3                   1.25.10                    py_0  
watchdog                  0.10.3           py38haf1e3a3_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
wheel                     0.34.2                   py38_0  
wrapt                     1.11.2           py38h1de35cc_0  
wurlitzer                 2.0.1                    py38_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
yapf                      0.30.0                     py_0  
zeromq                    4.3.2                hb1e8313_2  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h1de35cc_3  

Note: you may need to restart the kernel to use updated packages.

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : environment_name
    active env location : /usr/local/anaconda3/envs/environment_name
            shell level : 2
       user config file : /Users/username/.condarc
 populated config files : /Users/username/.condarc
          conda version : 4.8.4
    conda-build version : 3.18.11
         python version : 3.7.7.final.0
       virtual packages : __osx=10.15.6
       base environment : /usr/local/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /Users/username/.conda/pkgs
       envs directories : /usr/local/anaconda3/envs
                          /Users/username/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.7 Darwin/19.6.0 OSX/10.15.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False


Note: you may need to restart the kernel to use updated packages.

```
</details>

### PR DESCRIPTION
**Pull request by Lucurus**
Simply rebuild the package for extended Python support (See https://github.com/conda/conda/issues/10156#issuecomment-673769286) as outlined in README.md.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Should fix #8 and fix #3.

This is my first pull request here, please delete if incorrect.

### CODE REVIEW

**Comment by Lucurus** [comment]
@conda-forge-admin, please rerender

**Comment by Lucurus** [comment]
Just to confirm, we are only waiting on @mrandrewandrade's feedback, correct? Or do I have to do something before merge?

**Comment by liZe** [comment]
> Just to confirm, we are only waiting on @mrandrewandrade's feedback, correct?

I think so.

**Comment by Lucurus** [comment]
Ok, because I don't have write access so I cannot merge it. Not sure what your access is?

**Comment by liZe** [comment]
> Ok, because I don't have write access so I cannot merge it. Not sure what your access is?

I can merge if needed.

**Comment by Lucurus** [comment]
> I can merge if needed.

Ok, then it's up to you if you want to wait for @mrandrewandrade or want to merge directly as I can't.

**Comment by liZe** [comment]
> Ok, then it's up to you if you want to wait for @mrandrewandrade or want to merge directly as I can't.

It’s pretty straightforward, I think that we can merge.

**Pull request merged**
